### ISSUE TITLE
Will you be doing dual tvl1?

### ISSUE THREAD

**Issue by hollowgalaxy** [rfezzani/pyimof#1]
Or can you give some pointers on how to alter your code to match dual tvl1?

**Comment by rfezzani** [comment]
Hi @hollowgalaxy, the `pyimof.solvers.tvl1` is already the dual TV-L1algorithm (see the [doc](https://pyimof.readthedocs.io/en/latest/pyimof.html#pyimof.solvers.tvl1)) ;-)

**Comment by hollowgalaxy** [comment]
Awesome. Thanks. Really helpful repo.

**Comment by rfezzani** [comment]
You welcome ;-) Thank you @hollowgalaxy for your interest in pyimof

**Comment by hollowgalaxy** [comment]
I finally had a chance to compare your implementation with the one in cv2 using this code...
```
import matplotlib.pyplot as plt
import pyimof
import cv2
import numpy as np

print(cv2.__version__) # 4.1.0
I0, I1 = pyimof.data.hydrangea()
dof = cv2.optflow.createOptFlow_DualTVL1()
flow = dof.calc(I0=np.expand_dims(I0, axis=-1), I1=np.expand_dims(I1, axis=-1), flow=None)
u = flow[...,0]
v = flow[...,1]
# u, v = pyimof.solvers.tvl1(I0, I1)

pyimof.display.plot(u, v)
plt.show()
```
There is a slight difference.
Here is cv2's solution
![image](https://user-images.githubusercontent.com/52365584/61256461-bd1c0400-a721-11e9-9a8b-d25440e58dc8.png)
Here is your solution (showing here for easy comparison)
![image](https://user-images.githubusercontent.com/52365584/61256505-da50d280-a721-11e9-99d0-b88023b1308c.png)

Seems that the cv2 implimenation is more coarse. My thought would have been that this signifies its better. Or does smoother pixel transition indicate better results?

**Comment by rfezzani** [comment]
hi @hollowgalaxy, obtaining sharp optical flow at object border is a great challenge. In fact these regions are usually the occlusion areas, (_ie_ areas where the optical flow problem is undefined).

The answer to your question basically depends on your application: if you want to use the optical flow for segmentation for example, sharp results are better. But if you want to estimate fluid motion (in [PIV](https://en.wikipedia.org/wiki/Particle_image_velocimetry) for example), there is no edges to fit, so smooth optical flow is OK.

Now if you look at the `pyimof.data.urban2` sequence for example, you will see that sharp result does not always mean good result: in fact `opencv` output is sharp but not good at all:

![cv2_urban2](https://user-images.githubusercontent.com/3438227/61285680-ac22cf80-a7c1-11e9-8360-628adc94f446.png)

 compared to `pyimov`

![pyimof_urban2](https://user-images.githubusercontent.com/3438227/61285714-b93fbe80-a7c1-11e9-83f5-e2d4b0272ef1.png)

and the ground truth optical flow:

![gt_urban2](https://user-images.githubusercontent.com/3438227/61286001-3b2fe780-a7c2-11e9-9eee-7191d825bd16.png)

**Comment by hollowgalaxy** [comment]
Wow. Awesome answer. I appreciate the detail you went through. I was wondering why that noise was appearing in the cv2 implementation. Looks like it was just that, noise.
