### ISSUE TITLE
Vector field quiver plot for sequence

### ISSUE THREAD

**Issue by HamidGadirov** [rfezzani/pyimof#5]
Hi,

I am wondering how can I use the quiver plot to visualize flow not only for a pair of images but for a sequence where the length of the arrows as well as their color should be relative. For instance, in the plot below all arrows have the same length and color, however, in that simulation the values of the flow in x and y dimensions change, so does the magnitude. 
<img width="1511" alt="seq" src="https://user-images.githubusercontent.com/39424882/214452748-dfba1676-b4da-4393-ad81-d8e0a7a3e78d.png">
How can this be taken into account and visualized properly using pyimof?

**Comment by rfezzani** [comment]
Hello @HamidGadirov, and thank you for your interest in `pyimof`.
I didn't tested it, but I think that you may achieve what you expect by scaling all your displacement fields according to a common scaling factor.
```python
scale_factor = 5  # Arbitrary large enough value
for u, v in OF_SEQ:
    u /= scale_factor
    v /= scale_factor
```
`scale_factor` can be the maximum displacement magnitude in the full sequence.

**Comment by HamidGadirov** [comment]
Hi @rfezzani , thanks for the suggestion, I tried to scale the flow vectors when I am visualizing the results and after I compute the norm, e.g. like this:
```
u_gt = flow_u_gt
v_gt = flow_v_gt
norm_gt = np.sqrt(u_gt * u_gt + v_gt * v_gt)
pyimof.display.quiver(u_gt / scale_factor, v_gt / scale_factor, c=norm_gt, bg=img, ax=ax, cmap='jet', bg_cmap='gray', step=quiver_steps)
```
but it didn't lead to any difference in terms of visualization. All vectors still have the same length and red color no matter which `scale_factor` I have, even a very large one. If I scale before computing the norm, there is no difference either. That changes only if I have different magnitude vectors within each image.

**Comment by rfezzani** [comment]
After a deeper exploration, it turns out that the solution is simpler then it looks. [`pyimof.display.quiver`]( https://pyimof.readthedocs.io/en/latest/pyimof.html#pyimof.display.quiver) accepts any kwarg supported by [`matplotlib.pyplot.quiver`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.quiver.html) and `clim` is exactly what you are looking for:
```python
import numpy as np
import pyimof
from matplotlib import pyplot as plt

plt.ion()


u = np.random.rand(460, 640)
v = np.random.rand(460, 640)
c = np.sqrt(u * u + v * v)

alpha = 1.2

ax = pyimof.display.quiver(u, v, c, clim=(-5, 5))
for _ in range(50):
    u *= alpha
    v *= alpha
    c *= alpha
    pyimof.display.quiver(u, v, c, ax=ax, clim=(-5, 5))
    input("Press any key")
```

**Comment by HamidGadirov** [comment]
Thanks for your suggestions, looks like using `clim` improves the visualization of the sequence indeed. I got now the quiver plots with different colors depending on the flow values (I think in this case `clim` operates with magnitude though, so min. value for `clim` should be 0). However, after taking a closer look I noticed that the length of the arrows is still the same no matter which flow values are in the corresponding time step:
<img width="1512" alt="Screenshot 2023-02-01 at 14 31 45" src="https://user-images.githubusercontent.com/39424882/216020337-2cab39d8-a00a-4ab1-94bd-15ed8394710a.png">
Do you have any suggestions for getting arrows with different lengths as well?

**Comment by rfezzani** [comment]
Again, the solution is in `matplotlib.pyplot.quiver` arguments :wink: : you need to set the `scale` argument to a value different then `None`

```python
import numpy as np
import pyimof
from matplotlib import pyplot as plt

plt.ion()


u = np.random.rand(460, 640)
v = np.random.rand(460, 640)
c = np.sqrt(u * u + v * v)

scale = 1

alpha = 1.2

ax = pyimof.display.quiver(u, v, c, clim=(0, 5), scale=scale)
for _ in range(50):
    ax.clear()
    u *= alpha
    v *= alpha
    c *= alpha
    pyimof.display.quiver(u, v, c, ax=ax, clim=(0, 5), scale=scale)
    input("Press any key")
```
I hope it solves your problem.

**Comment by HamidGadirov** [comment]
Thanks @rfezzani, this is what I was looking for.
